img1 = imread('SS CA2\\Images\image02.jpg');
img2 = rgb2gray(img1);
img2 = im2double(img2);
F = fft2(img2);
F_shift = fftshift(F);
[M, N] = size(img2);
centerX = N / 2;
centerY = M / 2;
cutoff = 60;
[X, Y] = meshgrid (1:N, 1:M);
D = sqrt((X - centerX).^2 + (Y - centerY).^2);
H_high = double(D > cutoff);
G_high_shift = F_shift .* H_high;
img_high = real(ifft2(ifftshift(G_high_shift)));
figure;
tiledlayout(1,2);
nexttile;
imshow(img1);
nexttile;
imshow(img_high);
